# Generated by Django 2.2 on 2019-04-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Get_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_data', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
    ]
