# Generated by Django 2.2 on 2019-05-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_get_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_data', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
    ]
