# Generated by Django 2.2 on 2019-05-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_send_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('room', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('status', models.BooleanField(blank=True)),
            ],
        ),
    ]
