# Generated by Django 2.2 on 2019-05-02 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Send_data',
        ),
        migrations.DeleteModel(
            name='Topmenu',
        ),
    ]
