# Generated by Django 2.2 on 2019-04-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='普通会员表',
            name='生日',
            field=models.DateField(blank=True, null=True),
        ),
    ]
